spring:
  datasource:
    initialSize: 5
    minIdle: 5
    maxActive: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    dbone:
      jdbcUrl: jdbc:postgresql://192.168.49.62:5432/xiaoya_finance
      userName: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    dbtwo:
      jdbcUrl: jdbc:postgresql://192.168.49.62:5432/xiaoya_finance
      userName: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
mybatis:
  configuration:
   map-underscore-to-camel-case: true #开启驼峰映射